In [2]:
%matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd
from PIL import Image
from tqdm import tqdm

In [4]:
train_features = pd.read_csv("../train_features.csv", index_col="id")
test_features = pd.read_csv("../test_features.csv", index_col="id")
train_labels = pd.read_csv("../train_labels.csv", index_col="id")

In [5]:
train_features.head()

                             filepath   site
id
ZJ000000  train_features/ZJ000000.jpg  S0120
ZJ000001  train_features/ZJ000001.jpg  S0069
ZJ000002  train_features/ZJ000002.jpg  S0009
ZJ000003  train_features/ZJ000003.jpg  S0008
ZJ000004  train_features/ZJ000004.jpg  S0036

In [6]:
test_features.head()

                            filepath   site
id
ZJ016488  test_features/ZJ016488.jpg  S0082
ZJ016489  test_features/ZJ016489.jpg  S0040
ZJ016490  test_features/ZJ016490.jpg  S0040
ZJ016491  test_features/ZJ016491.jpg  S0041
ZJ016492  test_features/ZJ016492.jpg  S0040

In [7]:
train_labels.head()

,antelope_duiker,bird,blank,civet_genet,hog,leopard,monkey_prosimian,rodent
id,,,,,,,,
ZJ000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
ZJ000001,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
ZJ000002,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
ZJ000003,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
ZJ000004,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0